backend:
  name: github
  repo: v0id-user/peace-land
  branch: main
  auth_type: pkce
  app_id: Ov23li9gnuXAbwoHn5ra

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
